### ISSUE TITLE
[Deep Learning] 나이 예측시 Regression or Classification?

### ISSUE THREAD

**Issue by dlcjfgmlnasa** [dlcjfgmlnasa/Detection_Face_Information#3]
- [ ] 나이를 1~100 output을 출력해주는 Regression 모델로 개발
- [x] 나이를 1~100 output을 출력해주는 Classification 모델로 개발
- [x] 나이를 범주화(categories) 시켜 출력해주는 Classification 모델로 개발

**Comment by dlcjfgmlnasa** [comment]
**나이를 1~100 output을 출력해주는 Regression 모델로 개발**

- epoch : 8
- 전체 모델 Loss : 4.8765
- 성별 모델 정확도 : 0.9449 👍 
- 나이 모델 정확도 : 0.1100 👎 

![image](https://user-images.githubusercontent.com/17635204/72597362-f479a080-3950-11ea-97b1-435f27d63b30.png)

`결론`: 
- 학습횟수가 부족하지만 모델의 정확도가 많이 올라가지 않음
- 50 이상의 나이를 가지는 Face 학습데이터가 절대적으로 부족하기 때문으로 판단
- 따라서 모델을 **Regression** 방법으로 수정 혹은 **나이를 범주화** 시키는 방법으로 변환해야된다고 판단

**Comment by hyungsseop** [comment]
**나이를 1~100 까지 출력해주는 Regression 모델 개발을 위한 참조링크**
- https://github.com/Sakura03/age_trans

**Comment by dlcjfgmlnasa** [comment]
## 나이를 카테고리화 하기로 확정
- 10대. 20대. 30대 ... 등등
